### ISSUE TITLE
new track played to death

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#221]
As noted in TODO: Currently, any track added after the system's been up for a while will be played to death.

Workaround, manually reset `played` column in database.

I think that in the first version of the App we were enqueueing (there’s that vowel-heavy word again) all the tracks at once, so that a track wouldn’t be repeated until each unique track had been played once.

I like the idea of dynamically equalizing the played counts by prioritizing less-popular tracks, but imagine that another approach would be to dynamically updated the played count of each new track to match the (average, lowest) play counts of others.

**Comment by Rosuav** [comment]
I think the 'played' field in the database should remain as it is - an accurate statistical field. It's the selection process that needs to change. Maybe something like that a track can't be autopicked (the queue is, of course, independent) until at least N/2 others have been picked, where N is the number of active tracks in the database.

**Comment by MikeiLL** [comment]
Another thing that's happening at the moment is that the same tracks are ending up close to one another in the stream. With the above recommendation above, we would have at least 1/2 of the chunks played before the potential of one being repeated, correct?

**Comment by Rosuav** [comment]
Okay, here's a plan. Whenever *any* track is requested, the database selects N/2 IDs and enqueues them (but without ticking up their enqueued counters). They get shuffled and fed to the renderer one by one.

**Comment by MikeiLL** [comment]
"(but without ticking up their enqueued counters)" do you mean without ticking up their _played_ counters?

**Comment by Rosuav** [comment]
No, they also have enqueued counters for the number of times they've been explicitly put onto the queue. Their played counters will go up once they get pulled off the queue and played.

**Comment by MikeiLL** [comment]
Why can't we populate the queue with all the active tracks and refill it when it's empty?

**Comment by Rosuav** [comment]
Because then, the last few become inevitable - we're "due" for this one. Randomness shouldn't work that way.

**Comment by Rosuav** [comment]
Fixed by #224.

**Comment by Rosuav** [comment]
Just found another good reason not to populate the queue too soon: everything gets loaded from the database at enqueue time. That means there's latency on changes to the database equal to the length of the queue, which means we want to keep it short. Database changes include stored analysis and (once that's implemented) itrim/otrim.

**Comment by MikeiLL** [comment]
Makes sense.
