### ISSUE TITLE
Incorporate Trim configurations from database

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#222]
Some of the tracks definitely need trimming.

In pydub this is trivial. we could update `renderer.infinitely_glitch()` as follows:

    # remove itrim and otrim
    itrim = nexttrack.track_details['itrim']; otrim = nexttrack.track_details['otrim']
    dub2 = dub2[itrim:otrim]

Then when we analyze the first and last beats with Amen, we we insure that they are at times _after_ `itrim` and _previous_ to `otrim`.

Each Amen `timeslice` in `timings['beats']` contains a start time: `t1.timings['beats'][-1].time`, so I think if we update the list indexing here: `b.duration.value for b in t1b[-1-LAST_BEAT_AVG : -1]` we can get first and last beats _inside_ of the `itrim` and `otrim` parameters.

**Comment by Rosuav** [comment]
Do they have something other than silence that needs to be trimmed?

**Comment by MikeiLL** [comment]
Some of them definitely do. The ones from the Glitch recording studio have a whole long tail end. Other's have smaller trim tweaks for the managed Major Glitch in sequence.
