### ISSUE TITLE
Override Crossfade

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#239]
Admin would like to be able to override the automatic crossfade. 

My idea for front end was a checkbox on the manage_transition page and inserting a -1 into the xfade field in the database to signify a hard transition. 

Looked around the renderer a bit. Expecting that the parameter would need to get, ultimately to `infinitely_glitch()` both for `render_all()` and `render_audition()`.

I see that both of those functions are enqueueing into `_track_queue`, and that that's what `infinitely_glitch()` pulls from via `get_track_to_play()`.

Would it make sense to send a parameter to infinitely_glitch() telling it to consider `nexttrack.track_details["xfade"]`, and if it `= -1`, don't overlay?

**Comment by Rosuav** [comment]
By "not overlay", you mean that the normal behaviour of finding a beat should be bypassed, and the entire trailer and leader be kept?

**Comment by MikeiLL** [comment]
yes. exactly. `...TRACKA ][ TRACKB...`

**Comment by Rosuav** [comment]
Not too hard. I'll see what I can do.

**Comment by MikeiLL** [comment]
Great.

**Comment by Rosuav** [comment]
See #240
