### ISSUE TITLE
Hard Transition

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#241]
If we render the last 10 seconds of track A with a hard transition into the last ten seconds of track B the total length should be twenty seconds.

Can we make a function that tests that?

**Comment by Rosuav** [comment]
You can see it implicitly by watching the debug log of how much output gets rendered. It should sum to twenty seconds.

**Comment by Rosuav** [comment]
And if you do an audition render, it's even clearer, because the last info-level message is the rendered length.

**Comment by MikeiLL** [comment]
Perfect.
