### ISSUE TITLE
App should load over https

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/appension#246]
This looks like a [useful tutorial](https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https). However it may make more sense to use [Cloudflare SSL](https://www.cloudflare.com/ssl/).

**Comment by Rosuav** [comment]
Since you're using gunicorn, it should be as easy as adding a couple of parameters to the command line:

https://stackoverflow.com/questions/7406805/running-gunicorn-on-https

Getting a cert could possibly be done with Cloudflare, or alternatively using LetsEncrypt and certbot.

**Comment by MikeiLL** [comment]
> Since you're using gunicorn, it should be as easy as adding a couple of parameters to the command line:
> 
> https://stackoverflow.com/questions/7406805/running-gunicorn-on-https
> 
> Getting a cert could possibly be done with Cloudflare, or alternatively using LetsEncrypt and certbot.

Installed the certs via Let's Encrypt and they are:

```
/etc/letsencrypt/live/infiniteglitch.net/
cert.pem  chain.pem  fullchain.pem  privkey.pem
```

So I think that perhaps I should be running

```
gunicorn --certfile=/etc/letsencrypt/live/infiniteglitch.net/fullchain.pem --keyfile=/etc/letsencrypt/live/infiniteglitch.net/privkey.pem --bind 0.0.0.0:443 glitch.server:app
```

Does it make sense to go ahead and run that command?

Note, I generated these keys manually with [Letsencrypt](https://github.com/letsencrypt/letsencrypt) and manually added routes to the server to verify the pairs. So am afraid that this approach will not work for auto renewing.

**Comment by MikeiLL** [comment]
When I followed [this approach](https://certbot.eff.org/lets-encrypt/debianjessie-other) and ran

```
sudo /usr/local/bin/certbot-auto certonly --webroot
```
I put in `/home/mikekilmer/appension` as the web root, which is where the bot placed `.acme-challenge`, but that did not make `example.com/.acme-challenge/etc...` available.

Wondering if the solution is to create a Flask route which actually delivers the content of a specified directory, which would be entered as the path to web root in the `certbot-auto` process.
